import type { ExchangeCard, Interaction, Member, Project } from "./types";

/** 圖表分類色盤（已通過 CVD 驗證，奶油色底） */
export const PALETTE = [
  "#c8102e", "#2a78d6", "#eda100", "#1baf7a",
  "#4a3aa7", "#eb6834", "#e87ba4", "#008300",
];

export const DEMO_MEMBERS: Member[] = [
  {
    id: "m1", name: "王小明", company: "康誠醫療器材", industry: "醫療健康",
    chapter: "富樂分會", title: "業務總監", phone: "0912-345-678", line: "wang_kc",
    email: "wang@kangcheng.tw", website: "https://kangcheng.tw",
    facebook: "kangcheng.medical", instagram: "kangcheng_med", linkedin: "wang-hsiaoming",
    role: "admin", color: "#c8102e", media: {},
  },
  {
    id: "m2", name: "李大華", company: "仁華復健診所", industry: "醫療健康",
    chapter: "富樂分會", title: "院長", phone: "0922-111-222", line: "dr_lee",
    email: "lee@renhua.tw", website: "https://renhua.tw",
    facebook: "renhua.clinic", instagram: "renhua_rehab", linkedin: "lee-dahua",
    role: "member", color: "#2a78d6", media: {},
  },
  {
    id: "m3", name: "陳美玲", company: "美玲空間設計", industry: "室內設計",
    chapter: "富樂分會", title: "設計總監", phone: "0933-222-333", line: "ml_design",
    email: "chen@mldesign.tw", website: "https://mldesign.tw",
    facebook: "ml.interior", instagram: "ml_interior", linkedin: "chen-meiling",
    role: "member", color: "#eda100", media: {},
  },
  {
    id: "m4", name: "林志豪", company: "豪邸房產", industry: "房地產",
    chapter: "富樂分會", title: "店長", phone: "0955-333-444", line: "howhouse",
    email: "lin@howhouse.tw", website: "https://howhouse.tw",
    facebook: "howhouse.tw", instagram: "howhouse_tw", linkedin: "lin-chihhao",
    role: "member", color: "#1baf7a", media: {},
  },
  {
    id: "m5", name: "張雅婷", company: "雅信會計師事務所", industry: "會計財稅",
    chapter: "富樂分會", title: "會計師", phone: "0966-444-555", line: "cpa_chang",
    email: "chang@yaxin.tw", website: "https://yaxin.tw",
    facebook: "yaxin.cpa", instagram: "", linkedin: "chang-yating",
    role: "member", color: "#4a3aa7", media: {},
  },
  {
    id: "m6", name: "黃國倫", company: "倫格法律事務所", industry: "法律服務",
    chapter: "富樂分會", title: "主持律師", phone: "0977-555-666", line: "lawyer_huang",
    email: "huang@lunge.law", website: "https://lunge.law",
    facebook: "lunge.law", instagram: "", linkedin: "huang-kuolun",
    role: "member", color: "#eb6834", media: {},
  },
  {
    id: "m7", name: "吳佩珊", company: "珊瑚整合行銷", industry: "行銷廣告",
    chapter: "富樂分會", title: "創辦人", phone: "0988-666-777", line: "coral_mkt",
    email: "wu@coralmkt.tw", website: "https://coralmkt.tw",
    facebook: "coral.marketing", instagram: "coral_mkt", linkedin: "wu-peishan",
    role: "member", color: "#e87ba4", media: {},
  },
  {
    id: "m8", name: "劉建宏", company: "宏遠數位科技", industry: "網頁/軟體開發",
    chapter: "富樂分會", title: "技術長", phone: "0910-777-888", line: "hy_tech",
    email: "liu@hongyuan.dev", website: "https://hongyuan.dev",
    facebook: "hongyuan.dev", instagram: "", linkedin: "liu-chienhung",
    role: "member", color: "#008300", media: {},
  },
  {
    id: "m9", name: "蔡淑芬", company: "芬芳手作烘焙", industry: "餐飲食品",
    chapter: "卓越分會", title: "負責人", phone: "0921-888-999", line: "fenfang_bake",
    email: "tsai@fenfang.tw", website: "https://fenfang.tw",
    facebook: "fenfang.bakery", instagram: "fenfang_bakery", linkedin: "",
    role: "member", color: "#c8102e", media: {},
  },
  {
    id: "m10", name: "周文傑", company: "傑印精緻印刷", industry: "印刷包裝",
    chapter: "卓越分會", title: "總經理", phone: "0932-999-000", line: "jayprint",
    email: "chou@jayprint.tw", website: "https://jayprint.tw",
    facebook: "jayprint.tw", instagram: "jayprint", linkedin: "chou-wenchieh",
    role: "member", color: "#2a78d6", media: {},
  },
];

export const DEMO_CARDS: ExchangeCard[] = [
  {
    memberId: "m1",
    updatedAt: "2026-07-10T09:30:00Z",
    answers: {
      s1_sources: { BNI: 30, 舊客戶: 40, 陌生開發: 20, 展覽: 10 },
      s1_years: "5–10 年", s1_team: "11–30 人", s1_revenue_model: "長期合約",
      s1_new_clients: "3–5 位", s1_trend: "穩定持平",
      s1_focus: ["開發新客源", "建立合作聯盟"],
      s1_challenge: "醫療院所採購週期長，需要更多院所端的信任引薦。",
      s2_dream_case: "中大型復健科、骨科診所的整批醫療設備採購案。",
      s2_decision_maker: ["企業主／負責人", "採購窗口"],
      s2_company_size: ["10–50 人中小企業", "政府／學校／機構"],
      s2_budget: "20–100 萬", s2_cycle: "一季內",
      s2_signals: ["展店／擴點", "法規變動"],
      s2_want_to_meet: "診所院長、醫療院所採購主管、長照機構負責人。",
      s3_tenure: "2–5 年", s3_121_per_month: "5–8 次",
      s3_ref_given: "2–4 個", s3_ref_received: "2–4 個",
      s3_close_rate: "30–50%", s3_bni_share: "10–30%", s3_satisfaction: 4,
      s3_improve: ["121 深度交流", "跨分會交流"],
      s4_coop_methods: ["互相引薦客戶", "聯合提案投標", "共同行銷曝光"],
      s4_target_industries: ["醫療健康", "保險理財", "室內設計"],
      s4_upstream: "診所裝修設計完成後就需要設備進場；保險夥伴的醫療客戶也常有設備需求。",
      s4_downstream: "設備售出後，院所需要維護保養、醫療行銷與人才招募。",
      s4_events: ["主題講座", "展覽／市集"],
      s4_cross_sell: "高：可主動打包銷售", s4_profit_model: ["轉介客戶", "優惠方案"],
      s5_121_target: "6 次", s5_121_list: "李大華（醫療）、陳美玲（室內設計）、張雅婷（財稅）",
      s5_ref_target: "4 個", s5_key_coop: "與李院長合辦復健照護講座，帶動設備展示。",
      s5_help_needed: ["引薦特定對象", "活動曝光支援"],
      s5_success_look: "完成 6 場 121、拿下一家診所整批設備案。",
      s6_intro_60: "我幫診所用最合理的預算，配好一整間的復健與醫療設備。",
      s6_ideal_customer: "新開業或擴點中的復健科、骨科、物理治療所，決策者是院長。",
      s6_no_go: "二手設備削價競標案、無醫療證照的美容工作室。",
      s6_coop_flow: "引薦後 3 天內拜訪 → 免費場地規劃 → 報價 → 交機與教育訓練。",
      s6_success_case: "協助新開幕復健診所在 45 天內完成全院設備建置，準時開幕。",
      s6_resources_give: ["供應商網絡", "專業知識／講師", "客戶名單交換"],
      s6_resources_need: ["行銷曝光／社群流量", "客戶名單交換", "活動合辦"],
      s6_company_line: "康誠醫療器材－診所開業設備的一站式夥伴。",
      s6_regions: ["台北市", "新北市", "桃園市"],
      s6_industries: ["醫療健康"],
      s6_cross_region: "可以", s6_out_of_city: "接受",
      s6_open_projects: "復健診所整廠設備專案：徵室內設計與財稅夥伴，鎖定新開業診所，預計 Q4 前簽約。",
    },
  },
  {
    memberId: "m2",
    updatedAt: "2026-07-09T14:00:00Z",
    answers: {
      s1_sources: { 舊客戶: 50, 網路: 20, BNI: 15, Google: 15 },
      s1_years: "10 年以上", s1_team: "6–10 人", s1_revenue_model: "訂閱／回購制",
      s1_new_clients: "11–30 位", s1_trend: "明顯成長",
      s1_focus: ["拓展服務區域", "建立合作聯盟"],
      s1_challenge: "門診量成長快，但院所空間與設備擴充的規劃人力不足。",
      s2_dream_case: "企業員工健康照護合作案、運動傷害防護長期配合。",
      s2_decision_maker: ["企業主／負責人", "人資部門"],
      s2_company_size: ["50–200 人中型企業", "200 人以上大型企業"],
      s2_budget: "20–100 萬", s2_cycle: "一個月內",
      s2_signals: ["大量徵才", "季節性需求"],
      s2_want_to_meet: "企業人資長、健康講座主辦單位、醫療設備供應商。",
      s3_tenure: "1–2 年", s3_121_per_month: "2–4 次",
      s3_ref_given: "5–8 個", s3_ref_received: "2–4 個",
      s3_close_rate: "50% 以上", s3_bni_share: "10% 以下", s3_satisfaction: 4,
      s3_improve: ["主題簡報能力"],
      s4_coop_methods: ["互相引薦客戶", "教育訓練交流", "提供場地資源"],
      s4_target_industries: ["醫療健康", "保險理財", "人力資源"],
      s4_upstream: "保險理財顧問的客戶常需要復健照護；企業人資是重要入口。",
      s4_downstream: "病患復原後常詢問健身、營養與保險規劃。",
      s4_events: ["主題講座", "工作坊／課程", "公益活動"],
      s4_cross_sell: "中：可視案件搭配", s4_profit_model: ["轉介客戶", "資源共享"],
      s5_121_target: "4 次", s5_121_list: "王小明（醫療器材）、吳佩珊（行銷）",
      s5_ref_target: "6 個", s5_key_coop: "與設備夥伴合辦社區復健講座。",
      s5_help_needed: ["活動曝光支援", "名單交換"],
      s5_success_look: "簽下一家企業健康照護年約。",
      s6_intro_60: "我讓上班族的痠痛，在下班後一小時內被好好照顧。",
      s6_ideal_customer: "重視員工健康的中大型企業、需要運動防護的球隊與健身房。",
      s6_no_go: "純醫美諮詢、與復健無關的掛名合作。",
      s6_coop_flow: "引薦後由專人安排評估 → 制定照護方案 → 每月成效回報。",
      s6_success_case: "為科技公司 300 名員工建立季度健檢與物理治療通道。",
      s6_resources_give: ["場地空間", "專業知識／講師", "客戶名單交換"],
      s6_resources_need: ["供應商網絡", "行銷曝光／社群流量", "活動合辦"],
      s6_company_line: "仁華復健診所－企業與家庭的復健照護夥伴。",
      s6_regions: ["台北市", "新北市"],
      s6_industries: ["醫療健康", "人力資源"],
      s6_cross_region: "視案件而定", s6_out_of_city: "視案件而定",
    },
  },
  {
    memberId: "m3",
    updatedAt: "2026-07-08T11:20:00Z",
    answers: {
      s1_sources: { 舊客戶: 35, BNI: 25, IG: 20, 合作夥伴: 20 },
      s1_years: "5–10 年", s1_team: "6–10 人", s1_revenue_model: "一次性專案",
      s1_new_clients: "3–5 位", s1_trend: "明顯成長",
      s1_focus: ["提高客單價", "品牌與行銷"],
      s1_challenge: "案件集中在住宅，想開拓診所與商空設計案源。",
      s2_dream_case: "300 萬以上的診所、辦公室與商業空間整體設計案。",
      s2_decision_maker: ["企業主／負責人", "高階主管"],
      s2_company_size: ["10 人以下小型企業", "10–50 人中小企業"],
      s2_budget: "100–500 萬", s2_cycle: "一季內",
      s2_signals: ["公司搬遷／裝修", "展店／擴點"],
      s2_want_to_meet: "要開業的診所院長、展店中的餐飲品牌、商辦房仲。",
      s3_tenure: "2–5 年", s3_121_per_month: "5–8 次",
      s3_ref_given: "5–8 個", s3_ref_received: "5–8 個",
      s3_close_rate: "30–50%", s3_bni_share: "30–50%", s3_satisfaction: 5,
      s3_improve: ["跨分會交流"],
      s4_coop_methods: ["互相引薦客戶", "共同行銷曝光", "聯合提案投標"],
      s4_target_industries: ["房地產", "醫療健康", "餐飲食品", "建築營造"],
      s4_upstream: "房仲成交後、診所租下新址後，就是設計進場的時機。",
      s4_downstream: "設計完工後客戶需要家具軟裝、設備進場與開幕行銷。",
      s4_events: ["主題講座", "聯名企劃"],
      s4_cross_sell: "高：可主動打包銷售", s4_profit_model: ["轉介客戶", "優惠方案"],
      s5_121_target: "6 次", s5_121_list: "林志豪（房產）、王小明（醫療設備）、蔡淑芬（烘焙）",
      s5_ref_target: "6 個", s5_key_coop: "與房產夥伴建立「成交即轉介」流程。",
      s5_help_needed: ["引薦特定對象"],
      s5_success_look: "簽下一件診所設計案，建立兩條穩定轉介線。",
      s6_intro_60: "我把冰冷的空間，變成會替你做生意的品牌門面。",
      s6_ideal_customer: "剛簽約新址的診所、餐飲與辦公室業主，預算 150 萬以上。",
      s6_no_go: "只做局部修繕的小工程、無限次比稿。",
      s6_coop_flow: "引薦後免費丈量 → 概念提案 → 簽約設計 → 工程監造。",
      s6_success_case: "打造北市復健診所旗艦空間，開幕月新患成長四成。",
      s6_resources_give: ["設計／製作產能", "供應商網絡", "異業合作通路", "客戶名單交換", "活動合辦"],
      s6_resources_need: ["客戶名單交換", "媒體／採訪管道"],
      s6_company_line: "美玲空間設計－商業空間的品牌化設計團隊。",
      s6_regions: ["台北市", "新北市", "桃園市", "新竹縣市"],
      s6_industries: ["室內設計"],
      s6_cross_region: "可以", s6_out_of_city: "接受",
    },
  },
  {
    memberId: "m4",
    updatedAt: "2026-07-07T16:45:00Z",
    answers: {
      s1_sources: { 舊客戶: 30, 網路: 30, BNI: 20, 陌生開發: 20 },
      s1_years: "10 年以上", s1_team: "11–30 人", s1_revenue_model: "一次性專案",
      s1_new_clients: "6–10 位", s1_trend: "穩定持平",
      s1_focus: ["開發新客源", "數位轉型"],
      s1_challenge: "商辦與店面物件去化速度慢，需要更多企業端買方。",
      s2_dream_case: "自用型商辦買賣、診所與品牌展店的店面租賃。",
      s2_decision_maker: ["企業主／負責人", "財務部門"],
      s2_company_size: ["10–50 人中小企業", "50–200 人中型企業"],
      s2_budget: "500 萬以上", s2_cycle: "半年以上",
      s2_signals: ["展店／擴點", "募資／增資", "公司搬遷／裝修"],
      s2_want_to_meet: "準備展店的連鎖品牌、要開業的醫師、企業第二代。",
      s3_tenure: "5 年以上", s3_121_per_month: "5–8 次",
      s3_ref_given: "9 個以上", s3_ref_received: "5–8 個",
      s3_close_rate: "10–30%", s3_bni_share: "10–30%", s3_satisfaction: 4,
      s3_improve: ["引薦品質訓練"],
      s4_coop_methods: ["互相引薦客戶", "共享通路資源"],
      s4_target_industries: ["室內設計", "法律服務", "會計財稅", "保險理財"],
      s4_upstream: "會計師與律師最早知道客戶要擴點、設立新公司。",
      s4_downstream: "成交後客戶立刻需要設計裝修、貸款保險與稅務規劃。",
      s4_events: ["商務餐會", "主題講座"],
      s4_cross_sell: "中：可視案件搭配", s4_profit_model: ["轉介客戶", "異業活動"],
      s5_121_target: "8 次", s5_121_list: "陳美玲（設計）、張雅婷（會計）、黃國倫（法律）",
      s5_ref_target: "8 個", s5_key_coop: "與設計、會計組成「展店鐵三角」服務包。",
      s5_help_needed: ["名單交換", "引薦特定對象"],
      s5_success_look: "成交一件商辦案並啟動鐵三角合作。",
      s6_intro_60: "企業要展店、醫師要開業，第一通電話先打給我。",
      s6_ideal_customer: "三年內要展店或購置自用辦公室的企業與診所。",
      s6_no_go: "純住宅低總價短期投機客。",
      s6_coop_flow: "需求訪談 → 物件短名單 → 陪同看屋 → 議價簽約 → 轉介裝修。",
      s6_success_case: "半年內替連鎖烘焙品牌找齊三家街邊店面。",
      s6_resources_give: ["客戶名單交換", "異業合作通路", "資金／投資人脈"],
      s6_resources_need: ["專業知識／講師", "行銷曝光／社群流量"],
      s6_company_line: "豪邸房產－企業展店與商辦置產的專業團隊。",
      s6_regions: ["台北市", "新北市", "桃園市"],
      s6_industries: ["房地產"],
      s6_cross_region: "可以", s6_out_of_city: "接受",
    },
  },
  {
    memberId: "m5",
    updatedAt: "2026-07-06T10:10:00Z",
    answers: {
      s1_sources: { 舊客戶: 60, BNI: 20, 合作夥伴: 20 },
      s1_years: "10 年以上", s1_team: "6–10 人", s1_revenue_model: "長期合約",
      s1_new_clients: "3–5 位", s1_trend: "穩定持平",
      s1_focus: ["提高客單價", "開發新產品／服務"],
      s1_challenge: "記帳業務利潤薄，想提高稅務顧問與新創設立服務比重。",
      s2_dream_case: "新設立公司的記帳簽證年約、跨境電商稅務顧問。",
      s2_decision_maker: ["企業主／負責人", "財務部門"],
      s2_company_size: ["10 人以下小型企業", "10–50 人中小企業"],
      s2_budget: "5–20 萬", s2_cycle: "一個月內",
      s2_signals: ["募資／增資", "法規變動", "展店／擴點"],
      s2_want_to_meet: "剛創業的負責人、要開分店的餐飲品牌、電商賣家。",
      s3_tenure: "2–5 年", s3_121_per_month: "2–4 次",
      s3_ref_given: "5–8 個", s3_ref_received: "2–4 個",
      s3_close_rate: "50% 以上", s3_bni_share: "10–30%", s3_satisfaction: 4,
      s3_improve: ["121 深度交流"],
      s4_coop_methods: ["互相引薦客戶", "教育訓練交流"],
      s4_target_industries: ["法律服務", "房地產", "電商零售", "餐飲食品"],
      s4_upstream: "律師處理公司設立後，記帳與稅務就是下一步。",
      s4_downstream: "客戶擴大後需要法律顧問、貸款與保險規劃。",
      s4_events: ["工作坊／課程", "主題講座"],
      s4_cross_sell: "低：先以引薦為主", s4_profit_model: ["轉介客戶", "資源共享"],
      s5_121_target: "4 次", s5_121_list: "黃國倫（法律）、林志豪（房產）",
      s5_ref_target: "4 個", s5_key_coop: "與律師推出「創業設立一條龍」方案。",
      s5_help_needed: ["引薦特定對象"],
      s5_success_look: "新增三家記帳年約客戶。",
      s6_intro_60: "創業第一年最容易踩的稅務坑，我先幫你填平。",
      s6_ideal_customer: "設立三年內的公司與工作室，重視合規與節稅。",
      s6_no_go: "想做假帳避稅、資料長期不齊的客戶。",
      s6_coop_flow: "免費健檢 → 報價 → 簽年約 → 每月結帳與季度稅務會議。",
      s6_success_case: "協助烘焙品牌三家分店完成股權與稅務重整，年省稅六位數。",
      s6_resources_give: ["專業知識／講師", "政府補助資訊"],
      s6_resources_need: ["客戶名單交換", "異業合作通路"],
      s6_company_line: "雅信會計師事務所－中小企業的財稅後盾。",
      s6_regions: ["台北市", "新北市"],
      s6_industries: ["會計財稅"],
      s6_cross_region: "視案件而定", s6_out_of_city: "視案件而定",
    },
  },
  {
    memberId: "m6",
    updatedAt: "2026-07-05T09:00:00Z",
    answers: {
      s1_sources: { 舊客戶: 45, BNI: 25, 合作夥伴: 30 },
      s1_years: "5–10 年", s1_team: "2–5 人", s1_revenue_model: "混合型",
      s1_new_clients: "3–5 位", s1_trend: "穩定持平",
      s1_focus: ["開發新客源", "建立合作聯盟"],
      s1_challenge: "訴訟案件波動大，想增加企業法律顧問年約。",
      s2_dream_case: "中小企業常年法律顧問、商業合約審閱年約。",
      s2_decision_maker: ["企業主／負責人", "高階主管"],
      s2_company_size: ["10–50 人中小企業", "50–200 人中型企業"],
      s2_budget: "5–20 萬", s2_cycle: "一個月內",
      s2_signals: ["募資／增資", "法規變動", "大量徵才"],
      s2_want_to_meet: "成長期新創創辦人、連鎖加盟總部、人資主管。",
      s3_tenure: "1–2 年", s3_121_per_month: "2–4 次",
      s3_ref_given: "2–4 個", s3_ref_received: "2–4 個",
      s3_close_rate: "30–50%", s3_bni_share: "10–30%", s3_satisfaction: 3,
      s3_improve: ["121 深度交流", "主題簡報能力"],
      s4_coop_methods: ["互相引薦客戶", "聯合提案投標", "教育訓練交流"],
      s4_target_industries: ["會計財稅", "房地產", "人力資源"],
      s4_upstream: "會計師與房仲最早接觸到需要合約與盡調的客戶。",
      s4_downstream: "顧問客戶常需要財稅、勞資與智財的延伸服務。",
      s4_events: ["主題講座", "工作坊／課程"],
      s4_cross_sell: "低：先以引薦為主", s4_profit_model: ["轉介客戶", "資源共享"],
      s5_121_target: "4 次", s5_121_list: "張雅婷（會計）、林志豪（房產）",
      s5_ref_target: "4 個", s5_key_coop: "與會計師合開「創業法稅工作坊」。",
      s5_help_needed: ["引薦特定對象", "活動曝光支援"],
      s5_success_look: "簽下兩家企業法律顧問年約。",
      s6_intro_60: "合約先給我看三十分鐘，替你擋掉三年後的官司。",
      s6_ideal_customer: "10 人以上、有簽約量的中小企業與連鎖品牌。",
      s6_no_go: "純情感糾紛委任、要求保證勝訴的案件。",
      s6_coop_flow: "免費初談 → 法律風險健檢 → 顧問年約 → 每月諮詢時數。",
      s6_success_case: "替加盟總部重寫加盟合約，一年內零加盟糾紛。",
      s6_resources_give: ["專業知識／講師"],
      s6_resources_need: ["客戶名單交換", "行銷曝光／社群流量"],
      s6_company_line: "倫格法律事務所－中小企業的隨行法務長。",
      s6_regions: ["台北市", "新北市", "桃園市"],
      s6_industries: ["法律服務"],
      s6_cross_region: "可以", s6_out_of_city: "接受",
    },
  },
  {
    memberId: "m7",
    updatedAt: "2026-07-04T15:30:00Z",
    answers: {
      s1_sources: { 舊客戶: 40, IG: 25, BNI: 15, 合作夥伴: 20 },
      s1_years: "3–5 年", s1_team: "6–10 人", s1_revenue_model: "長期合約",
      s1_new_clients: "3–5 位", s1_trend: "明顯成長",
      s1_focus: ["擴編團隊", "開發新產品／服務"],
      s1_challenge: "客戶多在餐飲美業，想切入醫療與專業服務業的行銷案。",
      s2_dream_case: "月費 8 萬以上的品牌社群代操年約、診所開幕行銷案。",
      s2_decision_maker: ["企業主／負責人", "行銷部門"],
      s2_company_size: ["10 人以下小型企業", "10–50 人中小企業"],
      s2_budget: "5–20 萬", s2_cycle: "一個月內",
      s2_signals: ["新品上市", "展店／擴點", "公司搬遷／裝修"],
      s2_want_to_meet: "診所院長、新開幕店家、要做品牌重塑的傳產二代。",
      s3_tenure: "6 個月–1 年", s3_121_per_month: "5–8 次",
      s3_ref_given: "2–4 個", s3_ref_received: "5–8 個",
      s3_close_rate: "30–50%", s3_bni_share: "30–50%", s3_satisfaction: 5,
      s3_improve: ["引薦品質訓練"],
      s4_coop_methods: ["共同行銷曝光", "互相引薦客戶", "共同開發產品／服務"],
      s4_target_industries: ["醫療健康", "餐飲食品", "室內設計", "網頁/軟體開發"],
      s4_upstream: "設計完工、新店開幕、新品上市，都是行銷進場的時機。",
      s4_downstream: "行銷帶來流量後，客戶需要官網、電商系統與客服系統。",
      s4_events: ["直播／線上活動", "聯名企劃", "展覽／市集"],
      s4_cross_sell: "高：可主動打包銷售", s4_profit_model: ["轉介客戶", "優惠方案"],
      s5_121_target: "6 次", s5_121_list: "李大華（診所）、劉建宏（網頁）、蔡淑芬（烘焙）",
      s5_ref_target: "4 個", s5_key_coop: "與網頁夥伴推出「開幕行銷＋官網」套組。",
      s5_help_needed: ["引薦特定對象", "資源媒合"],
      s5_success_look: "簽下一件診所開幕行銷案。",
      s6_intro_60: "開幕前 90 天交給我，讓你開店第一天就排隊。",
      s6_ideal_customer: "半年內要開幕或改裝的店家與診所，願意投入月費行銷。",
      s6_no_go: "一次性發文小案、成效歸因不清的純廣告投放。",
      s6_coop_flow: "品牌健檢 → 90 天開幕企劃 → 內容執行 → 每月成效會議。",
      s6_success_case: "烘焙品牌開幕企劃讓首月營收超標 180%。",
      s6_resources_give: ["行銷曝光／社群流量", "媒體／採訪管道", "活動合辦"],
      s6_resources_need: ["技術開發", "客戶名單交換"],
      s6_company_line: "珊瑚整合行銷－開幕與品牌重塑的行銷推手。",
      s6_regions: ["台北市", "新北市", "台中市"],
      s6_industries: ["行銷廣告"],
      s6_cross_region: "可以", s6_out_of_city: "接受",
    },
  },
  {
    memberId: "m8",
    updatedAt: "2026-07-03T13:00:00Z",
    answers: {
      s1_sources: { 舊客戶: 50, 合作夥伴: 30, BNI: 20 },
      s1_years: "5–10 年", s1_team: "11–30 人", s1_revenue_model: "混合型",
      s1_new_clients: "0–2 位", s1_trend: "穩定持平",
      s1_focus: ["開發新客源", "開發新產品／服務"],
      s1_challenge: "案件單價高但週期長，需要穩定的年度維護客源。",
      s2_dream_case: "50 萬以上的品牌官網＋系統開發案、年度維護約。",
      s2_decision_maker: ["企業主／負責人", "行銷部門"],
      s2_company_size: ["10–50 人中小企業", "50–200 人中型企業"],
      s2_budget: "20–100 萬", s2_cycle: "一季內",
      s2_signals: ["新品上市", "募資／增資", "展店／擴點"],
      s2_want_to_meet: "要做電商的品牌主、行銷公司、預約系統需求的診所。",
      s3_tenure: "2–5 年", s3_121_per_month: "2–4 次",
      s3_ref_given: "2–4 個", s3_ref_received: "2–4 個",
      s3_close_rate: "10–30%", s3_bni_share: "10% 以下", s3_satisfaction: 3,
      s3_improve: ["121 深度交流", "引薦品質訓練"],
      s4_coop_methods: ["共同開發產品／服務", "互相引薦客戶", "聯合提案投標"],
      s4_target_industries: ["行銷廣告", "電商零售", "醫療健康"],
      s4_upstream: "行銷公司接到品牌案後，官網與系統就是我的進場點。",
      s4_downstream: "網站上線後客戶需要廣告投放、SEO 與內容經營。",
      s4_events: ["工作坊／課程", "直播／線上活動"],
      s4_cross_sell: "高：可主動打包銷售", s4_profit_model: ["轉介客戶", "優惠方案"],
      s5_121_target: "4 次", s5_121_list: "吳佩珊（行銷）、王小明（醫療）",
      s5_ref_target: "2 個", s5_key_coop: "與行銷夥伴組成數位轉型提案小組。",
      s5_help_needed: ["引薦特定對象"],
      s5_success_look: "與行銷夥伴共同拿下一件品牌官網案。",
      s6_intro_60: "我把你的生意搬上網，還讓它自動長出訂單。",
      s6_ideal_customer: "年營收 3000 萬以上、要做電商或系統化的品牌。",
      s6_no_go: "5 萬以下形象官網、無限修改的模板案。",
      s6_coop_flow: "需求訪談 → 系統規格書 → 分期開發 → 上線與年度維護。",
      s6_success_case: "替連鎖烘焙品牌建置電商，線上營收半年占比達三成。",
      s6_resources_give: ["技術開發", "設計／製作產能"],
      s6_resources_need: ["行銷曝光／社群流量", "客戶名單交換", "異業合作通路"],
      s6_company_line: "宏遠數位科技－中小企業的數位轉型工程隊。",
      s6_regions: ["台北市", "新北市", "台中市", "高雄市"],
      s6_industries: ["網頁/軟體開發"],
      s6_cross_region: "可以", s6_out_of_city: "接受",
    },
  },
  {
    memberId: "m9",
    updatedAt: "2026-07-02T08:40:00Z",
    answers: {
      s1_sources: { 舊客戶: 30, IG: 30, FB: 20, BNI: 20 },
      s1_years: "3–5 年", s1_team: "2–5 人", s1_revenue_model: "零售銷售",
      s1_new_clients: "30 位以上", s1_trend: "明顯成長",
      s1_focus: ["拓展服務區域", "開發新產品／服務"],
      s1_challenge: "節慶訂單爆量但平日量不穩，想開發企業禮盒常態訂單。",
      s2_dream_case: "企業年節禮盒大單、婚宴喜餅長期配合。",
      s2_decision_maker: ["行銷部門", "人資部門", "個人消費者"],
      s2_company_size: ["50–200 人中型企業", "200 人以上大型企業"],
      s2_budget: "1–5 萬", s2_cycle: "一週內",
      s2_signals: ["季節性需求", "婚喪喜慶／人生階段", "新品上市"],
      s2_want_to_meet: "企業福委會、人資主管、婚顧公司、飯店採購。",
      s3_tenure: "6 個月–1 年", s3_121_per_month: "2–4 次",
      s3_ref_given: "2–4 個", s3_ref_received: "5–8 個",
      s3_close_rate: "50% 以上", s3_bni_share: "30–50%", s3_satisfaction: 5,
      s3_improve: ["分會活動參與"],
      s4_coop_methods: ["互相引薦客戶", "共同行銷曝光", "提供場地資源"],
      s4_target_industries: ["印刷包裝", "行銷廣告", "人力資源", "旅遊休閒"],
      s4_upstream: "婚顧、企業人資與活動公司是禮盒訂單的最大來源。",
      s4_downstream: "禮盒訂單需要包裝印刷、物流與品牌設計。",
      s4_events: ["展覽／市集", "聯名企劃", "工作坊／課程"],
      s4_cross_sell: "高：可主動打包銷售", s4_profit_model: ["轉介客戶", "異業活動"],
      s5_121_target: "4 次", s5_121_list: "周文傑（印刷）、吳佩珊（行銷）",
      s5_ref_target: "4 個", s5_key_coop: "與印刷夥伴開發中秋聯名禮盒。",
      s5_help_needed: ["名單交換", "活動曝光支援"],
      s5_success_look: "拿下兩家企業中秋禮盒訂單。",
      s6_intro_60: "一盒手作點心，替你把心意送進客戶心裡。",
      s6_ideal_customer: "每年固定送禮的企業、籌備婚禮的新人。",
      s6_no_go: "低於成本的削價團購、代工貼牌。",
      s6_coop_flow: "試吃樣品 → 客製提案 → 打樣確認 → 準時交貨。",
      s6_success_case: "為上市公司客製 1200 盒年節禮盒，如期交付零客訴。",
      s6_resources_give: ["活動合辦", "異業合作通路"],
      s6_resources_need: ["設計／製作產能", "客戶名單交換", "行銷曝光／社群流量"],
      s6_company_line: "芬芳手作烘焙－企業禮贈與婚慶甜點的手作品牌。",
      s6_regions: ["台北市", "新北市", "基隆市"],
      s6_industries: ["餐飲食品"],
      s6_cross_region: "視案件而定", s6_out_of_city: "視案件而定",
    },
  },
  {
    memberId: "m10",
    updatedAt: "2026-07-01T17:15:00Z",
    answers: {
      s1_sources: { 舊客戶: 55, BNI: 25, 合作夥伴: 20 },
      s1_years: "10 年以上", s1_team: "11–30 人", s1_revenue_model: "混合型",
      s1_new_clients: "6–10 位", s1_trend: "略有下滑",
      s1_focus: ["開發新客源", "數位轉型", "建立合作聯盟"],
      s1_challenge: "傳統印刷量下滑，想轉向高質感包裝與品牌加值服務。",
      s2_dream_case: "品牌包裝設計印刷整合案、企業禮盒包材年約。",
      s2_decision_maker: ["企業主／負責人", "行銷部門", "採購窗口"],
      s2_company_size: ["10–50 人中小企業", "50–200 人中型企業"],
      s2_budget: "5–20 萬", s2_cycle: "一個月內",
      s2_signals: ["新品上市", "季節性需求", "展店／擴點"],
      s2_want_to_meet: "食品與美妝品牌主、行銷設計公司、電商賣家。",
      s3_tenure: "5 年以上", s3_121_per_month: "2–4 次",
      s3_ref_given: "5–8 個", s3_ref_received: "2–4 個",
      s3_close_rate: "30–50%", s3_bni_share: "10–30%", s3_satisfaction: 4,
      s3_improve: ["跨分會交流", "分會活動參與"],
      s4_coop_methods: ["互相引薦客戶", "共同開發產品／服務", "共享通路資源"],
      s4_target_industries: ["餐飲食品", "行銷廣告", "電商零售", "美容美業"],
      s4_upstream: "行銷與設計公司定稿後，印製就是必經的下一站。",
      s4_downstream: "印好包裝的品牌接著需要物流、通路與行銷曝光。",
      s4_events: ["展覽／市集", "聯名企劃"],
      s4_cross_sell: "中：可視案件搭配", s4_profit_model: ["轉介客戶", "異業活動"],
      s5_121_target: "4 次", s5_121_list: "蔡淑芬（烘焙）、吳佩珊（行銷）",
      s5_ref_target: "6 個", s5_key_coop: "與烘焙夥伴完成中秋禮盒包裝聯名。",
      s5_help_needed: ["引薦特定對象", "資源媒合"],
      s5_success_look: "簽下兩件品牌包裝整合案。",
      s6_intro_60: "好產品值得好包裝，我讓你的品牌在貨架上先被拿起來。",
      s6_ideal_customer: "重視質感的食品、美妝與禮贈品牌。",
      s6_no_go: "急件低價名片大宗印刷、盜版侵權印件。",
      s6_coop_flow: "打樣提案 → 材質確認 → 印製 → 品檢交貨。",
      s6_success_case: "替手作烘焙品牌設計禮盒包裝，隔年回購率達九成。",
      s6_resources_give: ["設計／製作產能", "供應商網絡"],
      s6_resources_need: ["客戶名單交換", "行銷曝光／社群流量"],
      s6_company_line: "傑印精緻印刷－品牌包裝的印製整合夥伴。",
      s6_regions: ["台北市", "新北市", "桃園市"],
      s6_industries: ["印刷包裝"],
      s6_cross_region: "可以", s6_out_of_city: "接受",
    },
  },
];

/** 2026 年 6–7 月的互動紀錄（121／轉介／合作／共同客戶） */
export const DEMO_INTERACTIONS: Interaction[] = [
  // --- 7 月 121 ---
  { id: "i1", type: "121", fromId: "m1", toId: "m2", date: "2026-07-02", note: "討論診所設備與講座合辦" },
  { id: "i2", type: "121", fromId: "m1", toId: "m3", date: "2026-07-06", note: "診所空間設計與設備配置" },
  { id: "i3", type: "121", fromId: "m3", toId: "m4", date: "2026-07-03", note: "成交即轉介流程對焦" },
  { id: "i4", type: "121", fromId: "m4", toId: "m5", date: "2026-07-08", note: "展店客戶的稅務需求" },
  { id: "i5", type: "121", fromId: "m5", toId: "m6", date: "2026-07-09", note: "創業法稅工作坊籌備" },
  { id: "i6", type: "121", fromId: "m7", toId: "m8", date: "2026-07-05", note: "開幕行銷＋官網套組" },
  { id: "i7", type: "121", fromId: "m9", toId: "m10", date: "2026-07-07", note: "中秋聯名禮盒打樣" },
  { id: "i8", type: "121", fromId: "m2", toId: "m7", date: "2026-07-10", note: "診所社群行銷規劃" },
  { id: "i9", type: "121", fromId: "m1", toId: "m5", date: "2026-07-11", note: "設備進口稅務諮詢" },
  // --- 6 月 121 ---
  { id: "i10", type: "121", fromId: "m1", toId: "m4", date: "2026-06-12", note: "診所展店選址" },
  { id: "i11", type: "121", fromId: "m3", toId: "m7", date: "2026-06-18", note: "完工案例聯合曝光" },
  { id: "i12", type: "121", fromId: "m6", toId: "m4", date: "2026-06-20", note: "商辦租約審閱合作" },
  { id: "i13", type: "121", fromId: "m8", toId: "m2", date: "2026-06-25", note: "診所預約系統需求" },
  { id: "i14", type: "121", fromId: "m9", toId: "m7", date: "2026-06-26", note: "品牌開幕企劃" },
  // --- 轉介 ---
  { id: "r1", type: "referral", fromId: "m4", toId: "m3", date: "2026-07-04", note: "商辦成交轉介裝修設計", amount: 1800000, closed: true },
  { id: "r2", type: "referral", fromId: "m3", toId: "m1", date: "2026-07-08", note: "診所設計案轉介設備採購", amount: 650000, closed: true },
  { id: "r3", type: "referral", fromId: "m2", toId: "m1", date: "2026-07-09", note: "同業診所設備需求", amount: 420000, closed: false },
  { id: "r4", type: "referral", fromId: "m5", toId: "m6", date: "2026-07-06", note: "客戶股權糾紛諮詢", amount: 120000, closed: true },
  { id: "r5", type: "referral", fromId: "m7", toId: "m8", date: "2026-07-07", note: "品牌客戶官網改版", amount: 500000, closed: false },
  { id: "r6", type: "referral", fromId: "m9", toId: "m10", date: "2026-07-05", note: "禮盒包裝印製", amount: 180000, closed: true },
  { id: "r7", type: "referral", fromId: "m4", toId: "m6", date: "2026-06-15", note: "購屋合約審閱", amount: 80000, closed: true },
  { id: "r8", type: "referral", fromId: "m4", toId: "m5", date: "2026-06-22", note: "新公司設立記帳", amount: 96000, closed: true },
  { id: "r9", type: "referral", fromId: "m10", toId: "m9", date: "2026-06-28", note: "企業客戶訂購手作禮盒", amount: 150000, closed: true },
  { id: "r10", type: "referral", fromId: "m7", toId: "m9", date: "2026-06-30", note: "開幕活動甜點桌", amount: 60000, closed: true },
  // --- 合作 ---
  { id: "c1", type: "cooperation", fromId: "m1", toId: "m2", date: "2026-06-30", note: "社區復健講座合辦" },
  { id: "c2", type: "cooperation", fromId: "m9", toId: "m10", date: "2026-07-01", note: "中秋聯名禮盒" },
  { id: "c3", type: "cooperation", fromId: "m7", toId: "m8", date: "2026-06-20", note: "數位轉型提案小組" },
  { id: "c4", type: "cooperation", fromId: "m5", toId: "m6", date: "2026-06-10", note: "創業法稅一條龍" },
  // --- 共同客戶 ---
  { id: "s1", type: "shared_client", fromId: "m3", toId: "m4", date: "2026-06-05", note: "連鎖烘焙展店案" },
  { id: "s2", type: "shared_client", fromId: "m1", toId: "m2", date: "2026-06-08", note: "復健診所開業案" },
  { id: "s3", type: "shared_client", fromId: "m7", toId: "m9", date: "2026-06-12", note: "烘焙品牌行銷案" },
];

/** 示範專案（Projects）：每位會員可建立多個專案 */
export const DEMO_PROJECTS: Project[] = [
  {
    id: "p1",
    memberId: "m1",
    name: "復健診所整廠設備專案",
    intro: "鎖定新開業與擴點的復健科診所，提供從評估、採購到安裝的一站式設備方案。",
    idealReferrals: "近期籌備開業或擴點的復健科、骨科診所院長。",
    industriesNeeded: ["室內設計", "會計財稅", "保險理財"],
    resourcesOffered: "醫療設備展示中心場地、院所端人脈、開業設備健檢服務。",
    expectedClose: "2026 Q4",
    startDate: "2026-06-01",
    endDate: "2026-12-31",
    isMain: true,
    importance: 5,
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-07-05T08:00:00Z",
  },
  {
    id: "p2",
    memberId: "m1",
    name: "長照機構設備汰換",
    intro: "協助既有長照機構汰換老舊復健設備，含補助申請協助。",
    idealReferrals: "營運三年以上的長照機構負責人。",
    industriesNeeded: ["保險理財", "法律服務"],
    resourcesOffered: "補助申請經驗、設備租賃方案。",
    expectedClose: "2026 Q3",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    isMain: false,
    importance: 3,
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-05-20T08:00:00Z",
  },
  {
    id: "p3",
    memberId: "m3",
    name: "醫療空間設計主推案",
    intro: "主打診所、醫美空間的全案設計，含動線規劃與醫療法規配合。",
    idealReferrals: "籌備新診所或改裝的醫師、醫療機構。",
    industriesNeeded: ["醫療健康", "建築營造", "房地產"],
    resourcesOffered: "醫療空間作品集、免費丈量與初步配置建議。",
    expectedClose: "2026 Q4",
    startDate: "2026-05-01",
    endDate: "2027-01-31",
    isMain: true,
    importance: 5,
    createdAt: "2026-05-01T08:00:00Z",
    updatedAt: "2026-07-08T08:00:00Z",
  },
];
